CREATE TABLE `assessmentQuestions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`competencyId` int NOT NULL,
	`question` text NOT NULL,
	`questionType` enum('self_assessment','scenario','behavioral','knowledge') NOT NULL DEFAULT 'self_assessment',
	`option1` text NOT NULL,
	`option2` text NOT NULL,
	`option3` text NOT NULL,
	`option4` text NOT NULL,
	`option5` text NOT NULL,
	`score1` int DEFAULT 20,
	`score2` int DEFAULT 40,
	`score3` int DEFAULT 60,
	`score4` int DEFAULT 80,
	`score5` int DEFAULT 100,
	`difficulty` enum('easy','medium','hard') DEFAULT 'medium',
	`targetLevel` int DEFAULT 3,
	`usageCount` int DEFAULT 0,
	`correctRate` int DEFAULT 50,
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessmentQuestions_id` PRIMARY KEY(`id`)
);
